### ISSUE TITLE
[BUG] Notes not always saving

### ISSUE THREAD

**Issue by Git08hb** [ya27hw/equran_app#13]
https://github.com/ya27hw/equran_app/assets/97441502/bea9bc77-83b8-4953-911f-cebf4bc993aa

**Comment by ya27hw** [comment]
Aware of this. It is saved, but the favorites section doesn’t refresh unless you navigate away and back to it. I’ll see to it.

**Comment by ya27hw** [comment]
Thanks for the bug testing, appreciate it.

**Comment by ya27hw** [comment]
Fixed this issue
