### ISSUE TITLE
[Bug] Favorites Tab is just white

### ISSUE THREAD

**Issue by Git08hb** [ya27hw/equran_app#15]
Happened with the newest update.

[
![Screenshot_20240513-032042](https://github.com/ya27hw/equran_app/assets/97441502/9f117b1b-2b7c-46b3-8f2b-a059f5a44f3a)

**Comment by ya27hw** [comment]
I can’t seem to reproduce this. Try clearing favorites first, does it persist?

**Comment by Git08hb** [comment]
> I can’t seem to reproduce this. Try clearing favorites first, does it persist?
> […](#)
> Message ID: ***@***.***>

Worked after clearing the favorites
