### ISSUE TITLE
Please make the app offline

### ISSUE THREAD

**Issue by Gamer750** [ya27hw/equran_app#2]
For better privacy

**Comment by ya27hw** [comment]
Internet is only required to stream verses

**Comment by Gamer750** [comment]
> Internet is only required to stream verses

So can't you just  change it to like this when you click play button you go to browser and download the audio and play the verse

**Comment by ya27hw** [comment]
An option to download the verses locally then play them offline in the app is something that I eventually want to implement. It’ll be coming soon.

**Comment by Gamer750** [comment]
> An option to download the verses locally then play them offline in the app is something that I eventually want to implement. It’ll be coming soon.

I mean the app should be completely offline

**Comment by ya27hw** [comment]
I can not make the app completely offline. This will comprise one of my core features, basically eliminating a reason why anyone would use this. 

Apps similar to mine on FDroid all require network access for the same reason.

**Comment by ya27hw** [comment]
> So can't you just change it to like this when you click play button you go to browser and download the audio and play the verse

This complicates things a lot, for just simply playing an audio file.
