### ISSUE TITLE
Feature to be able to choose the translator

### ISSUE THREAD

**Issue by Git08hb** [ya27hw/equran_app#5]
Selamun aleykum.

For example for English there are multiple translators like:

 Dr. Mustafa Khattab, The Clear Quran

and

Saheeh International (which is probably the current)

I want to be able to choose the translator

**Comment by ya27hw** [comment]
Wa Alaykum Salam
I’m currently using Saheeh Int as you mentioned. I’ll definitely add more translations, and languages.
Thank you for using my app!

**Comment by ya27hw** [comment]
I’ve added Clear Quran translation to the API I’ve been using. Just waiting for the dev to accept the PR. This should come within the next few days once everything goes well

**Comment by ya27hw** [comment]
completed in v1.2.7

**Comment by Git08hb** [comment]
Where are the apks for the new versions?

**Comment by ya27hw** [comment]
Should come to FDroid once they finish building apps, maybe takes 1-2 days.
There’s also a web version, available at quran.elbaesy.com

**Comment by Git08hb** [comment]
I'm using obtainium to get my updates straight from github. Could you upload the apks on github?

**Comment by ya27hw** [comment]
Done! If there’s any issue, do let me know

**Comment by Git08hb** [comment]
Barak Allahu Feek

Will do!
